<?php
declare(strict_types=1);

require_once __DIR__ . '/History.php';

/**
 * 排班算法核心入口（占位）。
 *
 * 历史统计已迁移至 History.php，本文件聚焦于未来的自动排班算法。
 * 当前阶段保留占位实现，确保模块结构完整，后续可逐步在此实现
 * 规则驱动的自动化排班流程。
 */

/**
 * 运行自动排班算法的占位实现。
 *
 * @param array<string,mixed> $context 输入上下文（成员、班次、限制条件等）
 *
 * @return array<string,mixed> 返回包含提示信息的占位结果
 */
function scheduler_run(array $context = []): array
{
    return [
        'meta' => [
            'autoGenerated' => false,
            'message' => '占位：请在 app/core/Scheduler.php 中实现自动排班算法。',
        ],
        'input' => $context,
    ];
}
